### ISSUE TITLE
Build failing due to broken dependency pygifsicle.

### ISSUE THREAD

**Issue by sasecio** [tvwenger/maxfield#31]
This is currently failing to build due to pygifsicle. 

```
Processing dependencies for maxfield==4.0
Searching for pygifsicle
Reading https://pypi.org/simple/pygifsicle/
Downloading https://files.pythonhosted.org/packages/03/4f/bde532b426d1f3969c74a1dfee79dde0a32c38005e29751d39c606f0334c/pygifsicle-1.0.4.tar.gz#sha256=a4332c461ee4a7564c22ef52000bcf9a624771b0c7376b4bf6fcf1ee1c3ecfcb
Best match: pygifsicle 1.0.4
Processing pygifsicle-1.0.4.tar.gz
Writing /tmp/easy_install-scf7v3lr/pygifsicle-1.0.4/setup.cfg
Running pygifsicle-1.0.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-scf7v3lr/pygifsicle-1.0.4/egg-dist-tmp-2gri4llp
Installing gifsicle on Linux requires sudo!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-scf7v3lr/pygifsicle-1.0.4/setup.py", line 52, in <module>
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

To workaround the problem, I grabbed [https://github.com/kohler/gifsicle](gifsicle) and removed the dependency requirement from setup.py.

**Comment by tvwenger** [comment]
Hmmm. I submitted a PR for pygifsicle to fix this a while ago: https://github.com/LucaCappelletti94/pygifsicle/pull/10

Will look into this. Thanks for reporting!

**Comment by tvwenger** [comment]
Ah, the problem is they haven't pushed the package to pypi since I submitted that PR.
https://github.com/LucaCappelletti94/pygifsicle/issues/11

The workaround is to install pygifsicle from Github, then install maxfield.

```
pip install git+https://github.com/LucaCappelletti94/pygifsicle.git
pip install git+https://github.com/tvwenger/maxfield.git
```

**Comment by tvwenger** [comment]
pygifsicle has been updated on pypi, and maxfield is building now. Thanks again for reporting!

**Comment by sasecio** [comment]
There we go! Nice and quick.

Thanks. Have a great day!
