### ISSUE TITLE
ValueError: total size of new array must be unchanged

### ISSUE THREAD

**Issue by audiocommander** [tvwenger/maxfield#4]
When I try to run the script (tested with two different input files), the script exits without output and I get this error:

```
python makePlan.py -n 1 -d portals.csv 
Found 35 portals in portal list.
Traceback (most recent call last):
  File "makePlan.py", line 375, in <module>
    main(**args)
  File "makePlan.py", line 163, in main
    xyz  = geometry.radstoxyz(locs)
  File "######/maxfield/lib/geometry.py", line 32, in radstoxyz
    pts = pts.reshape([-1,2])
ValueError: total size of new array must be unchanged
```

I can run the original script from jpeterbaker without problems. 
Might be a problem on my side though, as I have little to no python experience...

**Comment by tvwenger** [comment]
Could you upload or send me your portal list file?

**Comment by audiocommander** [comment]
Good hint!
I used the exporter plugin to generate a list with coordinates:

```
Catholic Church of the Holy Comforter; 38.031796,-78.479439
Congregation Beth Israel; 38.031893,-78.479082
Gen. Alexander Archer Vandegri; 38.03215,-78.478055
Stonewall Jackson Statue; 38.031918,-78.478089
```

When I changed this to use Intel Portal Links, it works!

```
Catholic Church of the Holy Comforter; https://www.ingress.com/intel?ll=38.031745,-78.478592&z=18&pll=38.031796,-78.479439
Congregation Beth Israel; https://www.ingress.com/intel?ll=38.031866,-78.47909&z=21&pll=38.031893,-78.479082
Gen. Alexander Archer Vandegri; https://www.ingress.com/intel?ll=38.031838,-78.478388&z=18&pll=38.03215,-78.478055
Stonewall Jackson Statue; https://www.ingress.com/intel?ll=38.031838,-78.478388&z=18&pll=38.031918,-78.478089
```

Hope this is helpful, thanks for the hint!
